server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
            scope:
              - email
              - profile
    debug: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/money-management

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG